version: '2.4'

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: '13.1'
      target: development
    image: twinkle.js:1.0.0
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    working_dir: /app
    command: yarn start
    environment:
      HISTFILE: /app/log/.bash_history
      LOG: ''
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
    volumes:
      - .:/app:cached
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./.psqlrc:/root/.psqlrc:ro
      - ./log:/var/log/psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
